import { CategoryInfo } from "@/types";

export const CATEGORIES: CategoryInfo[] = [
  {
    id: "protein-shakes",
    slug: "protein-shakes",
    name: "Protein Shakes",
    headline: "24g+ Protein Shakes for Energy & Recovery",
    description: "Thick, gourmet meal-replacement and post-workout shakes packed with 24g+ protein and vitamins.",
    iconName: "Flame",
    accentColor: "emerald",
    path: "/protein-shakes",
  },
  {
    id: "mega-teas",
    slug: "mega-teas",
    name: "Mega Energy Teas",
    headline: "Clean Herbal Energy & Botanical Hydration",
    description: "Vibrant, refreshing layered herbal teas with metabolism boosters, aloe, and zero sugar crash.",
    iconName: "Zap",
    accentColor: "amber",
    path: "/energy-teas",
  },
  {
    id: "acai",
    slug: "acai",
    name: "Açaí & Oatmeal Bowls",
    headline: "Fresh Superfood Bowls & Nourishing Warm Oats",
    description: "Antioxidant-rich açaí loaded with fresh fruits and hearty protein-infused warm oats.",
    iconName: "ShieldCheck",
    accentColor: "rose",
    path: "/acai-bowls",
  },
  {
    id: "waffles",
    slug: "waffles",
    name: "Protein Waffles & Bakery",
    headline: "Guilt-Free Waffles, Brownies & Cookies",
    description: "Freshly made protein waffles, chewy brownies, and soft-baked protein cookies.",
    iconName: "Cookie",
    accentColor: "orange",
    path: "/waffles-snacks",
  },
  {
    id: "specialties",
    slug: "specialties",
    name: "Specialty Drinks",
    headline: "Flavorful Latin-Inspired Wellness Specialties",
    description: "High-protein Horchata and refreshing sweet & spicy energizing Mangonada.",
    iconName: "Sparkles",
    accentColor: "purple",
    path: "/menu#specialties",
  },
  {
    id: "coffee",
    slug: "coffee",
    name: "Protein Coffee & Brews",
    headline: "VIP High-Protein Coffee & Classic Brews",
    description: "Rich espresso flavors with 15g+ protein plus smooth freshly brewed daily coffee.",
    iconName: "Coffee",
    accentColor: "stone",
    path: "/menu#coffee",
  },
];
